
let state={current:"noun",storyIndex:0,qIndex:0,correct:0,locked:false,stars:0,gems:0,cleared:{},seen:{},lastSpeech:""};
const DATA=window.GRAMMAR_GAME_DATA;
const colors=["#ff62c7","#8658f6","#ffd86b","#9af2bd","#7ed4ff","#ff9f1c","#ffffff"];
let deferredInstallPrompt=null;
window.addEventListener("beforeinstallprompt",(e)=>{e.preventDefault();deferredInstallPrompt=e;document.getElementById("installBtn").style.display="block"});
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;document.getElementById("installBtn").style.display="none"}else{alert("On iPhone, open in Safari and choose Share → Add to Home Screen.")}}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}
function E(x){return document.getElementById(x)}function child(){return E("childName").value.trim()||"Princess Helper"}function stage(){return DATA.stages.find(s=>s.id===state.current)}function pool(k){return DATA.wordPools[k]||[]}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function sample(a,n){return shuffle([...new Set(a)]).slice(0,n)}
function speechName(name){let n=name.trim();return DATA.pronunciationOverrides[n]||n.replace(/\bSia\b/g,"See-ah").replace(/\bSeah\b/g,"See-ah").replace(/세아/g,"See-ah")}
function speechText(t){let name=child();let spoken=speechName(name);return t.replaceAll(name,spoken).replace(/\bSia\b/g,"See-ah").replace(/\bSeah\b/g,"See-ah").replace(/세아/g,"See-ah")}
function saveSettings(){localStorage.setItem("pgg_v5_settings",JSON.stringify({child:E("childName").value,voice:E("voiceSelect").value}))}
function saveState(){localStorage.setItem("pgg_v5_state",JSON.stringify({stars:state.stars,gems:state.gems,cleared:state.cleared,seen:state.seen,current:state.current}))}
function load(){try{let s=JSON.parse(localStorage.getItem("pgg_v5_state")||"null");if(s)Object.assign(state,s);let set=JSON.parse(localStorage.getItem("pgg_v5_settings")||"null");if(set&&set.child)E("childName").value=set.child}catch(e){}}
function showScreen(x){["home","story","map","lesson","game","done","palace"].forEach(s=>E(s).classList.remove("on"));E(x).classList.add("on");let top=!(x==="home"||x==="story");E("top").style.display=top?"block":"none";E("foot").style.display=top&&x!=="palace"?"grid":"none";stats();window.scrollTo(0,0)}
function stats(){let c=Object.keys(state.cleared).length;E("cleared").textContent=c;E("total").textContent=DATA.stages.length;E("stars").textContent=state.stars;E("gems").textContent=state.gems;E("fill").style.width=c/DATA.stages.length*100+"%";E("next").textContent=c===DATA.stages.length?"Palace!":(DATA.stages.length-c)+" rooms";saveState()}
function asset(name){return `assets/${name}.svg`}
function goStory(){state.storyIndex=0;renderStory();showScreen("story")}
function renderStory(){let sl=DATA.story[state.storyIndex];let txt=sl[1].replace("Princess Helper",child());E("storyImg").src=asset(sl[0]);E("storyText").textContent=txt;E("storyBtn").textContent=state.storyIndex===DATA.story.length-1?"Go to Magic Map 🌈":"Next ✨";speak(txt,"hello")}
function nextStory(){if(state.storyIndex<DATA.story.length-1){state.storyIndex++;renderStory()}else goMap()}
function goMap(){let g=E("mapGrid");g.innerHTML="";DATA.stages.forEach((s,i)=>{let b=document.createElement("button");b.className="stage";b.innerHTML=`<div class="ico">${s.icon}</div><div><div class="st">${i+1}. ${s.title}</div><div class="sd">${s.grammar} · ${s.goal}</div></div><div class="mk">${state.cleared[s.id]?"💎":"✨"}</div>`;b.onclick=()=>chooseStage(s.id);g.appendChild(b)});E("wordbook").innerHTML=DATA.stages.map(s=>`<b>${s.grammar}</b>: ${pool(s.id).slice(0,95).join(", ")}${pool(s.id).length>95?", ...":""}<br><br>`).join("");showScreen("map")}
function chooseStage(id){state.current=id;if(state.seen[id])E("hint").classList.add("on");else renderLesson()}function closeHint(y){E("hint").classList.remove("on");y?renderLesson():startRound()}
function renderLesson(){let s=stage();state.seen[s.id]=1;E("lessonIcon").textContent=s.icon;E("lessonTitle").textContent=s.title+": "+s.grammar;E("lessonGoal").textContent=s.goal;E("lessonImage").src=asset(s.asset);let sentence=s.example.replace(/princess|crown|runs|pink|softly|She|is|and|under|a|Where/gi,m=>`<span class="hi">${m}</span>`);E("lessonBody").innerHTML=`<p>${s.explain}</p><div class="example"><div class="line">${sentence}</div><p>${s.note}</p></div><div class="tip">Princess Tip: ${s.tip}</div>`;speak(s.grammar+". "+s.explain+" Example. "+s.example);showScreen("lesson")}
function startRound(){state.qIndex=0;state.correct=0;renderQ();showScreen("game")}
let Q=null;function makeQ(){let s=stage();let right=sample(pool(s.id),1)[0];let wrong=sample(DATA.allWords.filter(w=>!pool(s.id).includes(w)),3);return{prompt:s.prompt,options:shuffle([right,...wrong]),answer:right,why:why(s.grammar,right),asset:s.asset}}
function why(g,w){return {"Noun":`${w} names something.`,"Verb":`${w} tells an action.`,"Adjective":`${w} describes something.`,"Adverb":`${w} can tell how, when, or where.`,"Pronoun":`${w} can replace a name or noun.`,"Be Verb":`${w} is a be verb.`,"Conjunction":`${w} connects words or ideas.`,"Preposition":`${w} can show place, direction, or relationship.`,"Article":`${w} is a tiny word before a noun.`,"Question Word":`${w} helps ask a question.`}[g]||`${w} is right.`}
function renderQ(){Q=makeQ();state.locked=false;let s=stage();E("roomPill").textContent=s.icon+" "+s.grammar;E("qPill").textContent=`Question ${state.qIndex+1}/10`;E("scorePill").textContent=`Correct ${state.correct}`;E("sceneImg").src=asset(Q.asset);E("prompt").textContent=Q.prompt;E("feedback").textContent="Choose one card.";E("nextBtn").style.display="none";E("options").innerHTML="";Q.options.forEach(o=>{let b=document.createElement("button");b.className="opt";b.textContent=o;b.onclick=e=>answer(b,o,e);E("options").appendChild(b)});speak(Q.prompt)}
function answer(b,o,e){if(state.locked)return;if(o===Q.answer){state.locked=true;state.correct++;state.stars++;b.classList.add("good");E("feedback").innerHTML=`Yes! <b>${o}</b> is right. ${Q.why} ⭐`;E("nextBtn").style.display="block";burst(48);spark(e);sound([880,1175,1397]);speak(`Wonderful, ${child()}! ${o} is right. ${Q.why}`,"wonderful")}else{b.classList.add("bad");E("feedback").innerHTML=`Almost. <b>${o}</b> is not the best answer. Try one more time.`;sound([240]);speak("Almost. Try one more time.","try_again");setTimeout(()=>b.classList.remove("bad"),650)}stats()}
function nextQuestion(){if(state.qIndex<9){state.qIndex++;renderQ()}else complete()}
function complete(){let s=stage();let pass=state.correct>=7;if(pass&&!state.cleared[s.id]){state.cleared[s.id]=1;state.gems++}stats();let c=Object.keys(state.cleared).length,r=DATA.rewards[Math.min(c-1,DATA.rewards.length-1)]||DATA.rewards[0];E("doneImg").src=asset(pass?s.asset:"princess");E("doneTitle").textContent=pass?"Magic Room Cleared!":"Good Try!";E("doneMsg").textContent=pass?`You got ${state.correct}/10. You earned one rainbow gem.`:`You got ${state.correct}/10. Try again to earn this room's rainbow gem.`;E("rewardGrid").innerHTML=pass?`<div class="rewardItem"><div class="em">💎</div>Rainbow Gem</div><div class="rewardItem"><div class="em">${r[0]}</div>${r[1]}</div>`:`<div class="rewardItem"><div class="em">🌟</div>Practice Star</div><div class="rewardItem"><div class="em">💪</div>Try Again</div>`;if(pass){burst(110);sound([523,659,784,1046]);speak(`Amazing, ${child()}! You cleared the magic room.`,"room_cleared")}Object.keys(state.cleared).length===DATA.stages.length?setTimeout(goPalace,1200):showScreen("done")}
function goPalace(){showScreen("palace");E("palaceMsg").textContent=`Great job, ${child()}! You cleared every grammar room.`;E("palaceRewards").innerHTML=DATA.rewards.map(r=>`<div class="rewardItem"><div class="em">${r[0]}</div>${r[1]}</div>`).join("");burst(180);sound([523,659,784,1046,1318]);speak(`Royal Palace unlocked! Great job, ${child()}!`,"palace_unlocked")}
function resetProgress(){state.stars=0;state.gems=0;state.cleared={};state.seen={};state.current="noun";stats();showScreen("home")}
function burst(n){let c=E("confetti");for(let i=0;i<n;i++){let s=document.createElement("span");s.style.left=Math.random()*100+"%";s.style.width=7+Math.random()*12+"px";s.style.height=10+Math.random()*16+"px";s.style.background=colors[Math.floor(Math.random()*colors.length)];s.style.animationDelay=Math.random()*260+"ms";c.appendChild(s);setTimeout(()=>s.remove(),1700)}}
function spark(e){let x=e?.clientX||innerWidth/2,y=e?.clientY||innerHeight/2;["🌸","✨","💖","⭐","🎉","💎"].forEach(t=>{let s=document.createElement("div");s.className="spark";s.textContent=t;s.style.left=x-16+Math.random()*46-23+"px";s.style.top=y-16+Math.random()*35-18+"px";document.body.appendChild(s);setTimeout(()=>s.remove(),950)})}
function voices(){if(!("speechSynthesis"in window))return;let vs=speechSynthesis.getVoices(),sel=E("voiceSelect"),saved=(JSON.parse(localStorage.getItem("pgg_v5_settings")||"{}").voice);sel.innerHTML="";vs.forEach(v=>{let o=document.createElement("option");o.value=v.name;o.textContent=`${v.name} (${v.lang})`;sel.appendChild(o)});let pref=saved||(vs.find(v=>/female|woman|girl|samantha|victoria|zira|jenny|aria|serena|karen|moira|emma|ava|susan/i.test(v.name))||vs.find(v=>/^en/i.test(v.lang))||vs[0]||{}).name;if(pref)sel.value=pref}
function getVoice(){let vs=speechSynthesis.getVoices(),sel=E("voiceSelect").value;return vs.find(v=>v.name===sel)||vs.find(v=>/^en/i.test(v.lang))||vs[0]}
function playMp3(key){return new Promise((resolve,reject)=>{let a=new Audio(`audio/${key}.mp3`);a.onended=resolve;a.onerror=reject;a.play().catch(reject)})}
function speak(t,key){state.lastSpeech=t;let text=speechText(t);if(key){playMp3(key).catch(()=>tts(text));}else tts(text)}
function tts(text){if(!("speechSynthesis"in window))return;let u=new SpeechSynthesisUtterance(text),v=getVoice();if(v)u.voice=v;u.rate=.78;u.pitch=1.32;u.volume=1;speechSynthesis.cancel();speechSynthesis.speak(u)}
function repeatVoice(){state.lastSpeech?speak(state.lastSpeech):previewVoice()}function previewVoice(){speak(`Hello ${child()}! I am the Rainbow Princess. Let's learn grammar magic together!`,"hello")}
function sound(notes){let A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!window.ctx)window.ctx=new A();notes.forEach((f,i)=>setTimeout(()=>{let o=ctx.createOscillator(),g=ctx.createGain();o.type="triangle";o.frequency.value=f;g.gain.value=.038;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.stop(ctx.currentTime+.18)},i*85))}
load();if("speechSynthesis"in window){voices();speechSynthesis.onvoiceschanged=voices}stats();
